<?php

namespace FluffyPaws\Services\Emails;

use Exception;
use Fluffy\Domain\Configuration\Config;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use RuntimeException;
use Swoole\ConnectionPool;
use Swoole\Coroutine\Http2\Client;
use Swoole\Http2\Request;
use Throwable;

class EmailConnector // extends ConnectionPool // ?? can it be http connection pool
{
    /**
     * Settings without which a send cannot work. Keys of `config.email`, mapped to the vault key
     * that fills them, so the diagnostic names the thing the operator has to go and fix.
     */
    private const REQUIRED_SETTINGS = [
        'host' => 'email_host',
        'from' => 'email_from',
        'username' => 'email_username',
        'password' => 'email_password',
        'SMTPSecure' => 'email_SMTPSecure',
        'port' => 'email_port',
    ];

    public function __construct(private Config $config) {}

    /**
     * Which mail settings are unusable, as human-readable reasons — empty array when mail is
     * configured.
     *
     * Three failure modes, and only the first is obvious from a stack trace:
     *
     *  - absent / empty: the key is not in the config at all;
     *  - the literal PLACEHOLDER TOKEN: `configs/app.php` is generated by substituting vault values
     *    into `configs/app.default.php`, and a substitution with nothing to substitute leaves the
     *    token behind. The SMTP host then IS the string "email_host" — a perfectly valid-looking
     *    setting that can only fail. This is what an empty or half-filled key vault looks like from
     *    inside the app, and it used to surface as a DNS error at send time with no hint of a cause.
     *
     * @return string[]
     */
    public function missingSettings(): array
    {
        $mailConfig = $this->config->values['email'] ?? null;
        if (!is_array($mailConfig)) {
            return ['config.email is missing entirely — configs/app.php has no email section'];
        }
        $problems = [];
        foreach (self::REQUIRED_SETTINGS as $key => $vaultKey) {
            $value = $mailConfig[$key] ?? null;
            if ($value === null || $value === '') {
                $problems[] = "email.$key is not set (vault key '$vaultKey')";
                continue;
            }
            // Any `email_*` string is a token the build failed to substitute — no real host,
            // address, password or port ever looks like that.
            if (is_string($value) && preg_match('/^email_[A-Za-z_]+$/', $value) === 1) {
                $problems[] = "email.$key is the UNSUBSTITUTED placeholder '$value' — the key vault "
                    . "had no value for '$vaultKey' when this release was built";
            }
        }
        return $problems;
    }

    /**
     * 
     * @param string $emailTo 
     * @param string $subject 
     * @param string $body 
     * @param string $emailName 
     * @param string $altBody 
     * @param null|EmailAttachment[] $attachments 
     * @return true[]|(false|string)[]|void 
     */
    public function send(string $emailTo, string $subject, string $body, string $emailName = '', string $altBody = '', ?array $attachments = null)
    {
        $mail = new PHPMailer(true);
        $mailConfig = $this->config->values['email'] ?? [];

        // Refused BEFORE the transport, because attempting it destroys the diagnosis: PHPMailer
        // reports a host of "email_host" as a DNS/connect failure, which reads like a network
        // problem on a box whose real problem is a key vault with nothing in it. The reasons go into
        // the returned message, so EmailLogService stores them on the EmailLog row too.
        $problems = $this->missingSettings();
        if ($problems !== []) {
            $time = date('Y-m-d H:i:s', time());
            echo "[Email] $time NOT SENT — email is not configured. To: $emailTo | Subject: $subject" . PHP_EOL;
            foreach ($problems as $problem) {
                echo "[Email]   - $problem" . PHP_EOL;
            }
            echo '[Email]   Fix: put the missing values in the key vault and rebuild '
                . '(the build now aborts on this instead of shipping placeholders).' . PHP_EOL;
            return ['success' => false, 'message' => 'Email is not configured: ' . implode('; ', $problems)];
        }

        if ($mailConfig['log_console'] ?? false) {
            print_r([
                "Outgoing Email:",
                $emailTo,
                $subject,
                $body,
                $emailName,
                $altBody,

            ]);
        }
        try {
            // Server settings
            $from = $mailConfig['from'];
            $mail->SMTPDebug = SMTP::DEBUG_OFF;
            $mail->isSMTP();
            $mail->Host       = $mailConfig['host'];
            $mail->SMTPAuth   = $mailConfig['SMTPAuth'];
            $mail->Username   = $mailConfig['username'];
            $mail->Password   = $mailConfig['password'];
            $mail->SMTPSecure = $mailConfig['SMTPSecure'];
            $mail->Port       = $mailConfig['port'];
            $mail->CharSet = PHPMailer::CHARSET_UTF8;
            // The domain PHPMailer uses for EHLO and the Message-ID. Left unset it falls back to
            // the machine's hostname — "DESKTOP-G4NJ8FT" on a dev box, the bare host on a server.
            // That is a non-FQDN HELO and a Message-ID whose domain doesn't match the sender, and
            // filters score both. Derive it from the From address so it always matches.
            $atPos = strrpos($from, '@');
            if ($atPos !== false) {
                $mail->Hostname = substr($from, $atPos + 1);
            }
            // Drop the "Using PHPMailer x.y.z" X-Mailer header: it names the library and exact
            // version in every message, and it reads as bulk mail. A single space disables it —
            // an empty string would restore the default.
            $mail->XMailer = ' ';
            // Recipients
            $mail->setFrom($from, $mailConfig['from_name'] ?? 'Notifications');
            $mail->addAddress($emailTo, $emailName);
            if (isset($mailConfig['copyTo'])) {
                $mail->addBCC($mailConfig['copyTo']);
            }
            // Content
            $mail->isHTML(true);
            $mail->Subject = $subject;
            $mail->Body    = $body;
            $mail->AltBody = $altBody;
            if ($attachments !== null) {
                foreach ($attachments as $attachment) {
                    $mail->addStringAttachment($attachment->Data, $attachment->FileName, PHPMailer::ENCODING_BASE64, $attachment->MimeType);
                }
            }
            // if it's additional domain
            // $mail->SMTPOptions = array(
            //     'ssl' => array(
            //         'verify_peer' => false,
            //         'verify_peer_name' => false,
            //         'allow_self_signed' => true
            //     )
            // );
            $time = date('Y-m-d H:i:s', time());
            echo "[Email] $time Sending email." . PHP_EOL;
            $mail->smtpClose();
            $mail->send();
            echo "[Email] $time Email has been sent." . PHP_EOL;
            return ['success' => true];
        } catch (Throwable $t) {
            $time = date('Y-m-d H:i:s', time());
            // WHAT was being sent and WHERE it was going. Without this the log says only "send
            // error" plus a stack trace, and there is no way to tell which email failed, to whom,
            // or against which SMTP endpoint — all of which decide what to do about it. The
            // password is the one thing never printed; every other setting is needed to diagnose.
            echo "[Email] $time Email send error." . PHP_EOL;
            echo "[Email]   to:      $emailTo" . (trim($emailName) !== '' ? " ($emailName)" : '') . PHP_EOL;
            echo "[Email]   subject: $subject" . PHP_EOL;
            echo '[Email]   smtp:    ' . ($mailConfig['username'] ?? '?') . '@'
                . ($mailConfig['host'] ?? '?') . ':' . ($mailConfig['port'] ?? '?')
                . ' (' . ($mailConfig['SMTPSecure'] ?? 'no encryption') . ', auth '
                . (($mailConfig['SMTPAuth'] ?? false) ? 'on' : 'off') . ')' . PHP_EOL;
            echo '[Email]   from:    ' . ($mailConfig['from'] ?? '?') . PHP_EOL;
            if (($mailConfig['password'] ?? '') === '') {
                echo '[Email]   NOTE: the SMTP password is EMPTY — the key vault has no email_password.' . PHP_EOL;
            }
            echo '[Email]   phpmailer: ' . ($mail->ErrorInfo !== '' ? $mail->ErrorInfo : '(nothing reported)') . PHP_EOL;
            echo '[Email]   exception: ' . get_class($t) . ' (' . $t->getCode() . ') ' . $t->getMessage() . PHP_EOL;
            echo $t->__toString() . PHP_EOL;
            // ErrorInfo is empty for anything thrown before PHPMailer sets it (a bad address, a
            // config type error) — falling back to the exception keeps the EmailLog row meaningful
            // instead of storing "Unknown error".
            $message = $mail->ErrorInfo !== '' ? $mail->ErrorInfo : get_class($t) . ': ' . $t->getMessage();
            return ['success' => false, 'message' => $message];
        }
    }
}
