<?php

namespace FluffyPaws\Services\Emails;

use Exception;
use Fluffy\Domain\Configuration\Config;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use RuntimeException;
use Swoole\ConnectionPool;
use Swoole\Coroutine\Http2\Client;
use Swoole\Http2\Request;
use Throwable;

class EmailConnector // extends ConnectionPool // ?? can it be http connection pool
{
    /**
     * Settings without which a send cannot work. Keys of `config.email`, mapped to the vault key
     * that fills them, so the diagnostic names the thing the operator has to go and fix.
     */
    private const REQUIRED_SETTINGS = [
        'host' => 'email_host',
        'from' => 'email_from',
        'username' => 'email_username',
        'password' => 'email_password',
        'SMTPSecure' => 'email_SMTPSecure',
        'port' => 'email_port',
    ];

    public function __construct(private Config $config) {}

    /**
     * A readable text/plain part for an HTML email.
     *
     * Every message is multipart/alternative, and filters compare the two parts: an HTML body with
     * a stub text part (or one that is merely the subject line repeated, which is what the activate
     * and reset emails used to send) is the shape of phishing, and mail-tester scores the resulting
     * text ratio directly. PHPMailer's own html2text is not usable here because it DROPS href
     * targets — the text part would say "click here to activate your account" and contain no link
     * at all, which is worse than none.
     *
     * So links are unwrapped first, as `label: url`, and the URL is omitted when the label already
     * IS the url (the visible-link fallback lines in the email templates) to avoid printing it twice.
     */
    public static function htmlToPlainText(string $html): string
    {
        // Anything non-textual, contents included — <style>/<script> bodies would otherwise survive
        // tag-stripping as a wall of CSS.
        $text = preg_replace('#<(style|script|head|title)\b[^>]*>.*?</\1>#is', '', $html) ?? $html;
        // Links become "label: url". Both are needed: the label carries the intent, the URL is what
        // a text-only reader has to be able to act on.
        $text = preg_replace_callback(
            '#<a\b[^>]*href\s*=\s*["\']([^"\']*)["\'][^>]*>(.*?)</a>#is',
            static function (array $m): string {
                $href = trim(html_entity_decode($m[1], ENT_QUOTES | ENT_HTML5, 'UTF-8'));
                $label = trim(preg_replace('#\s+#', ' ', strip_tags($m[2])) ?? '');
                // Padded, because adjacent inline anchors (the footer link row is exactly that)
                // would otherwise concatenate into "…/privacyTERMS: …". The whitespace collapse
                // below removes the surplus.
                if ($href === '' || $href === '#' || str_starts_with($href, 'mailto:')) {
                    return " $label ";
                }
                // The template's own "here is the raw URL" fallback line — one copy is enough.
                if ($label === '' || $label === $href) {
                    return " $href ";
                }
                return " $label: $href ";
            },
            $text
        ) ?? $text;
        // Block-level ends become line breaks before the tags go, or every paragraph runs together.
        $text = preg_replace('#<(br|/p|/div|/tr|/h[1-6]|/li)\b[^>]*>#i', "\n", $text) ?? $text;
        $text = strip_tags($text);
        $text = html_entity_decode($text, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        // Collapse the whitespace the table layout leaves behind: runs of spaces (NBSP included,
        // which the layout uses as spacer-cell filler) and runs of blank lines.
        $text = preg_replace('#[ \t\x{00A0}]+#u', ' ', $text) ?? $text;
        $text = preg_replace('#\s*\n\s*#', "\n", $text) ?? $text;
        $text = preg_replace('#\n{3,}#', "\n\n", $text) ?? $text;
        return trim($text);
    }

    /**
     * Which mail settings are unusable, as human-readable reasons — empty array when mail is
     * configured.
     *
     * Three failure modes, and only the first is obvious from a stack trace:
     *
     *  - absent / empty: the key is not in the config at all;
     *  - the literal PLACEHOLDER TOKEN: `configs/app.php` is generated by substituting vault values
     *    into `configs/app.default.php`, and a substitution with nothing to substitute leaves the
     *    token behind. The SMTP host then IS the string "email_host" — a perfectly valid-looking
     *    setting that can only fail. This is what an empty or half-filled key vault looks like from
     *    inside the app, and it used to surface as a DNS error at send time with no hint of a cause.
     *
     * @return string[]
     */
    public function missingSettings(): array
    {
        $mailConfig = $this->config->values['email'] ?? null;
        if (!is_array($mailConfig)) {
            return ['config.email is missing entirely — configs/app.php has no email section'];
        }
        $problems = [];
        foreach (self::REQUIRED_SETTINGS as $key => $vaultKey) {
            $value = $mailConfig[$key] ?? null;
            if ($value === null || $value === '') {
                $problems[] = "email.$key is not set (vault key '$vaultKey')";
                continue;
            }
            // Any `email_*` string is a token the build failed to substitute — no real host,
            // address, password or port ever looks like that.
            if (is_string($value) && preg_match('/^email_[A-Za-z_]+$/', $value) === 1) {
                $problems[] = "email.$key is the UNSUBSTITUTED placeholder '$value' — the key vault "
                    . "had no value for '$vaultKey' when this release was built";
            }
        }
        return $problems;
    }

    /**
     * 
     * @param string $emailTo 
     * @param string $subject 
     * @param string $body 
     * @param string $emailName 
     * @param string $altBody
     * @param null|EmailAttachment[] $attachments
     * @param null|array<string, string> $headers Extra headers, name => value.
     *
     *        Present for List-Unsubscribe, which NOTHING sets yet, deliberately. That header is a
     *        promise: receivers surface a one-click "unsubscribe" button from it, and Gmail expects
     *        the request to actually stop the mail. We have no unsubscribe endpoint and no
     *        notification preference to honour, so publishing one would advertise a control that
     *        does nothing — worse than omitting it. Gmail's bulk-sender requirement exempts
     *        transactional mail, which is all we currently send. Wire it when notification
     *        preferences exist, and never onto confirm-email or reset-password: there is no such
     *        thing as unsubscribing from a password reset you requested.
     * @return true[]|(false|string)[]|void
     */
    public function send(string $emailTo, string $subject, string $body, string $emailName = '', string $altBody = '', ?array $attachments = null, ?array $headers = null)
    {
        $mail = new PHPMailer(true);
        $mailConfig = $this->config->values['email'] ?? [];

        // Refused BEFORE the transport, because attempting it destroys the diagnosis: PHPMailer
        // reports a host of "email_host" as a DNS/connect failure, which reads like a network
        // problem on a box whose real problem is a key vault with nothing in it. The reasons go into
        // the returned message, so EmailLogService stores them on the EmailLog row too.
        $problems = $this->missingSettings();
        if ($problems !== []) {
            $time = date('Y-m-d H:i:s', time());
            echo "[Email] $time NOT SENT — email is not configured. To: $emailTo | Subject: $subject" . PHP_EOL;
            foreach ($problems as $problem) {
                echo "[Email]   - $problem" . PHP_EOL;
            }
            echo '[Email]   Fix: put the missing values in the key vault and rebuild '
                . '(the build now aborts on this instead of shipping placeholders).' . PHP_EOL;
            return ['success' => false, 'message' => 'Email is not configured: ' . implode('; ', $problems)];
        }

        if ($mailConfig['log_console'] ?? false) {
            print_r([
                "Outgoing Email:",
                $emailTo,
                $subject,
                $body,
                $emailName,
                $altBody,

            ]);
        }
        try {
            // Server settings
            $from = $mailConfig['from'];
            $mail->SMTPDebug = SMTP::DEBUG_OFF;
            $mail->isSMTP();
            $mail->Host       = $mailConfig['host'];
            $mail->SMTPAuth   = $mailConfig['SMTPAuth'];
            $mail->Username   = $mailConfig['username'];
            $mail->Password   = $mailConfig['password'];
            $mail->SMTPSecure = $mailConfig['SMTPSecure'];
            $mail->Port       = $mailConfig['port'];
            // PHPMailer defaults this to 300 SECONDS, and uses it for the connect as well as for
            // reads. A mail host that is unreachable — a provider that blocks outbound SMTP, a
            // firewall dropping the packets — therefore pins the Swoole task worker running this
            // send for five minutes, and a handful of queued emails takes the whole task pool with
            // it. Nothing about a submission connection legitimately takes 20s.
            $mail->Timeout = (int) ($mailConfig['timeout'] ?? 20);
            $mail->CharSet = PHPMailer::CHARSET_UTF8;
            // The domain PHPMailer uses for EHLO and the Message-ID. Left unset it falls back to
            // the machine's hostname — "DESKTOP-G4NJ8FT" on a dev box, the bare host on a server.
            // That is a non-FQDN HELO and a Message-ID whose domain doesn't match the sender, and
            // filters score both. Derive it from the From address so it always matches.
            $atPos = strrpos($from, '@');
            if ($atPos !== false) {
                $mail->Hostname = substr($from, $atPos + 1);
            }
            // Drop the "Using PHPMailer x.y.z" X-Mailer header: it names the library and exact
            // version in every message, and it reads as bulk mail. A single space disables it —
            // an empty string would restore the default.
            $mail->XMailer = ' ';
            // Recipients
            $mail->setFrom($from, $mailConfig['from_name'] ?? 'Notifications');
            $mail->addAddress($emailTo, $emailName);
            if (isset($mailConfig['copyTo'])) {
                $mail->addBCC($mailConfig['copyTo']);
            }
            // Content
            $mail->isHTML(true);
            $mail->Subject = $subject;
            $mail->Body    = $body;
            // A caller that supplied no text part, or supplied the subject line as one, gets a real
            // one derived from the HTML. Repeating the subject is treated as absent deliberately:
            // it was the shipped behaviour for confirm-email and reset-password, and a text part
            // that duplicates the Subject and carries no link is exactly what it means to have none.
            $trimmedAlt = trim($altBody);
            $mail->AltBody = ($trimmedAlt === '' || $trimmedAlt === trim($subject))
                ? self::htmlToPlainText($body)
                : $altBody;
            if ($headers !== null) {
                foreach ($headers as $headerName => $headerValue) {
                    $mail->addCustomHeader($headerName, $headerValue);
                }
            }
            if ($attachments !== null) {
                foreach ($attachments as $attachment) {
                    $mail->addStringAttachment($attachment->Data, $attachment->FileName, PHPMailer::ENCODING_BASE64, $attachment->MimeType);
                }
            }
            // if it's additional domain
            // $mail->SMTPOptions = array(
            //     'ssl' => array(
            //         'verify_peer' => false,
            //         'verify_peer_name' => false,
            //         'allow_self_signed' => true
            //     )
            // );
            $time = date('Y-m-d H:i:s', time());
            echo "[Email] $time Sending email." . PHP_EOL;
            $mail->smtpClose();
            $mail->send();
            echo "[Email] $time Email has been sent." . PHP_EOL;
            return ['success' => true];
        } catch (Throwable $t) {
            $time = date('Y-m-d H:i:s', time());
            // WHAT was being sent and WHERE it was going. Without this the log says only "send
            // error" plus a stack trace, and there is no way to tell which email failed, to whom,
            // or against which SMTP endpoint — all of which decide what to do about it. The
            // password is the one thing never printed; every other setting is needed to diagnose.
            echo "[Email] $time Email send error." . PHP_EOL;
            echo "[Email]   to:      $emailTo" . (trim($emailName) !== '' ? " ($emailName)" : '') . PHP_EOL;
            echo "[Email]   subject: $subject" . PHP_EOL;
            echo '[Email]   smtp:    ' . ($mailConfig['username'] ?? '?') . '@'
                . ($mailConfig['host'] ?? '?') . ':' . ($mailConfig['port'] ?? '?')
                . ' (' . ($mailConfig['SMTPSecure'] ?? 'no encryption') . ', auth '
                . (($mailConfig['SMTPAuth'] ?? false) ? 'on' : 'off') . ')' . PHP_EOL;
            echo '[Email]   from:    ' . ($mailConfig['from'] ?? '?') . PHP_EOL;
            if (($mailConfig['password'] ?? '') === '') {
                echo '[Email]   NOTE: the SMTP password is EMPTY — the key vault has no email_password.' . PHP_EOL;
            }
            echo '[Email]   phpmailer: ' . ($mail->ErrorInfo !== '' ? $mail->ErrorInfo : '(nothing reported)') . PHP_EOL;
            echo '[Email]   exception: ' . get_class($t) . ' (' . $t->getCode() . ') ' . $t->getMessage() . PHP_EOL;
            echo $t->__toString() . PHP_EOL;
            // ErrorInfo is empty for anything thrown before PHPMailer sets it (a bad address, a
            // config type error) — falling back to the exception keeps the EmailLog row meaningful
            // instead of storing "Unknown error".
            $message = $mail->ErrorInfo !== '' ? $mail->ErrorInfo : get_class($t) . ': ' . $t->getMessage();
            return ['success' => false, 'message' => $message];
        }
    }
}
